name: Update Latest Release Tag and All Release Tags

on:
  workflow_dispatch: # This event allows manual triggering of the workflow

jobs:
  update-release-tags:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Fetch Tags
      run: git fetch --tags

    - name: Get Latest Release Tag
      id: latest-tag
      run: |
        LATEST_RELEASE_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
        if [ -z "$LATEST_RELEASE_TAG" ]; then
          echo "No tags found in the repository."
          exit 1
        fi
        echo "tag:=$LATEST_RELEASE_TAG" >> $GITHUB_OUTPUT

      # echo "{name}={value}" >> $GITHUB_OUTPUT
    - name: Get All Release Tags
      id: all-tags
      run: |
        RELEASE_TAGS=($(git for-each-ref --format '%(refname:short)' refs/tags))
        echo $RELEASE_TAGS[*]
        echo "tags:=$RELEASE_TAGS[*]" >> $GITHUB_OUTPUT
    
    - name: Create or Update JSON
      run: |
        ALL_TAGS="[\"${{ steps.all-tags.outputs.tags }}\"]"
        echo '{"latest_release": "'${{ steps.latest-tag.outputs.tag }}'", "all_release_tags": '"$ALL_TAGS"'}' > latest-release.json
        # if [ -e "latest-release.json" ]; then
        #   # File exists, update it
        #   EXISTING_JSON="$(cat latest-release.json)"
        #   UPDATED_JSON=$(jq --arg latest_release "${{ steps.latest-tag.outputs.tag }}" --argjson all_release_tags "[${{ steps.all-tags.outputs.tags }}]" '.latest_release = $latest_release | .all_release_tags = $all_tags' <<< "$EXISTING_JSON")
        #   echo "$UPDATED_JSON" > latest-release.json
        # else
        #   # File does not exist, create it
        #   # Format all_tags as an array
        #   ALL_TAGS="[\"${{ steps.all-tags.outputs.tags }}\"]"
        #   echo '{"latest_release": "'${{ steps.latest-tag.outputs.tag }}'", "all_release_tags": '"$ALL_TAGS"'}' > latest-release.json
        # fi

    - name: Commit and Push
      run: |
        git config --local user.name "GitHub Actions"
        git config --local user.email "actions@github.com"
        git add .
        git commit -m "Update latest release tags"
        git push
